# -*- coding: utf-8 -*-
"""PREPROCESSING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15e5rZ0AN8Rghs3wc7X8fp01GaUbyM_h5
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("full_dataset.csv")
df.head()

df.info()

df = df[["text","category"]]
df.head()

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

#LOWERCASE
df["clean_text"] = df["text"].str.lower()
df.head()

#REMOVE SPECIAL CHARACTERS AND NUMBERS
df["clean_text"] = df["clean_text"].str.replace(r'[^a-z\s]','', regex=True)
df.head()

#REMOVE EXTRA SPACES
df["clean_text"] = df["clean_text"].str.replace(r'\s+',' ',regex=True).str.strip()
df.head()

#REMOVE STOPSWORDS
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
df["clean_text"] = df["clean_text"].apply(
    lambda x: " ".join(word for word in x.split() if word not in stop_words)
)
df.head()

#LEMMATIZATION
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
df["clean_text"] = df["clean_text"].apply(
    lambda x: " ".join(lemmatizer.lemmatize(word) for word in x.split())
)
df.head()

df[["text","clean_text"]].head()

#HIGH URGENCY WORDS LIST
high_words = ["urgent", "asap", "immediately", "refund", "failed", "error"]

#MEDIUM URGENCY WORDS LIST
medium_words = ["important", "soon", "please respond", "follow up"]

#LOW URGENCY WORDS LIST
df["urgency"] = "low"

#CONDITION
df.loc[
    df["clean_text"].str.contains("|".join(high_words), na=False),
    "urgency"
] = "High"
df

df["urgency"].value_counts()

df.loc[
    (df["clean_text"].str.contains("|".join(medium_words), na=False)) &
    (df["urgency"] == "Low"),
    "urgency"
] = "Medium"
df

df["urgency"].value_counts()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

x = df["clean_text"]
y = df["category"]
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)
print("x_train size:",x_train.shape)
print("x_test size:",x_test.shape)
print("y_train size:",y_train.shape)
print("y_test size:",y_test.shape)

#CONVERT TEXT TO NUMBERS(TF-IDF)
vectorized = TfidfVectorizer(max_features=5000)
x_train_vectorized = vectorized.fit_transform(x_train)
x_test_vectorized = vectorized.transform(x_test)
print(x_train_vectorized)
print(x_test_vectorized)

#TRAIN MODEL
model = LogisticRegression(max_iter=1000)
model.fit(x_train_vectorized, y_train)

#PREDICT
y_pred = model.predict(x_test_vectorized)
print("PREDICT")
print(y_pred)

#ACCURACY
print("Accuracy:",accuracy_score(y_test, y_pred))