# -*- coding: utf-8 -*-
"""tast_train_accuracy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGdQvHaIPLBas8wxT0r5_E0vfyBafgZW
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df_required = pd.read_csv('clean_email.csv')

# Input = clean email text
X = df_required["clean_text"].astype(str)

# Output = Category
y = df_required["Category"].astype(str)

print("Total samples:", len(X))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # keeps category balance
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X = df_required["clean_text"].astype(str)
y = df_required["Category"].astype(str)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2))
X_train_vec = tfidf.fit_transform(X_train)
X_test_vec  = tfidf.transform(X_test)

print("Train:", X_train_vec.shape, "Test:", X_test_vec.shape)

from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "Multinomial Naive Bayes": MultinomialNB(),
    "Linear SVM (LinearSVC)": LinearSVC(),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1),
}

results = []

for name, clf in models.items():
    clf.fit(X_train_vec, y_train)

    train_pred = clf.predict(X_train_vec)
    test_pred  = clf.predict(X_test_vec)

    train_acc = accuracy_score(y_train, train_pred)
    test_acc  = accuracy_score(y_test, test_pred)

    results.append((name, train_acc, test_acc))
    print(f"{name} -> Train: {train_acc:.4f} | Test: {test_acc:.4f}")

import pandas as pd

results_df = pd.DataFrame(results, columns=["Model", "Train_Accuracy", "Test_Accuracy"])
results_df = results_df.sort_values("Test_Accuracy", ascending=False).reset_index(drop=True)

results_df

from sklearn.metrics import classification_report

best_model_name = results_df.loc[0, "Model"]
print("Best Model:", best_model_name)

best_clf = models[best_model_name]
best_pred = best_clf.predict(X_test_vec)

print(classification_report(y_test, best_pred))